version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    expose:
      - "27017"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/music
  perfect_match:
    container_name: perfect_match
    build: .
    image: perfect_match/0.0.1
    ports:
      - "8081:8081"
      - "8443:8443"
    depends_on:
      - mongodb

      